# fly.toml app configuration file generated for campusconnect-9-lyra on 2025-09-10T20:55:42Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'campusconnect-9-lyra'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
